### ISSUE TITLE
Latitude and longitude inverted in NO FLIGHTS screen

### ISSUE THREAD

**Issue by FonceSlimane** [rzeldent/esp32-flightradar24-ttgo#13]
Hi 

It seems that the longitude and latitude displayed on the NO FLIGHTS screen are inverted

At line 192 of main.cpp, the code is:

tft.drawCentreString(format_latitude_longitude(center_longitude, center_latitude), TFT_HEIGHT / 2, TFT_WIDTH / 2 + 26, font_16pt);

but it should be:
tft.drawCentreString(format_latitude_longitude(center_latitude, center_longitude), TFT_HEIGHT / 2, TFT_WIDTH / 2 + 26, font_16pt);

Your last version is even better !
Thanks

(P.S : Maybe more challenging suggestion according to the size of screen of the TTGO : a pointer showing direction of the spotted airplane like an ADF )

**Comment by rzeldent** [comment]
Hi FonceSlimane,

lat/lon is fixed. Also some logo's are added from airlines that flew over...
I think there is really no space left for an ATF. Maybe some tweaking of the text could get some pixels.
However, keep this issue open for the future. A simple direction array might work?!

**Comment by FonceSlimane** [comment]
Yes a simple array could be fine (...with distance ? just an idea)
BTW, is it possible to modify the code in order to display flights even with missing data such as airport FROM or TO, A/C Type, or Flight Number ?
This could be especially useful with private, executive or non regular flights, where these datas are not always broadcasted.

Thanks

**Comment by rzeldent** [comment]
See latest commit; small direction arrow present.
Is too small...
