### ISSUE TITLE
issue with compass version

### ISSUE THREAD

**Issue by FonceSlimane** [rzeldent/esp32-flightradar24-ttgo#19]
Hi Rene,

Sorry to bother you, I can't try this new version with the compass feature
I have got these error messages when compiling:

src/main.cpp:68:1: error: 'Timezone' does not name a type
 Timezone timeZone(dst_begin, dst_end);
 ^
src/main.cpp: In function 'void setup()':
src/main.cpp:116:20: error: 'ntp_server_1' was not declared in this scope
   configTime(0, 0, ntp_server_1, ntp_server_2, ntp_server_3);
                    ^
src/main.cpp:116:34: error: 'ntp_server_2' was not declared in this scope
   configTime(0, 0, ntp_server_1, ntp_server_2, ntp_server_3);
                                  ^
src/main.cpp:116:48: error: 'ntp_server_3' was not declared in this scope
   configTime(0, 0, ntp_server_1, ntp_server_2, ntp_server_3);
                                                ^
src/main.cpp: In function 'void loop()':
src/main.cpp:310:9: error: 'TimeChangeRule' was not declared in this scope
         TimeChangeRule *tcr;
         ^
src/main.cpp:310:25: error: 'tcr' was not declared in this scope
         TimeChangeRule *tcr;
                         ^
src/main.cpp:311:22: error: 'timeZone' was not declared in this scope
         auto local = timeZone.toLocal(now, &tcr);
                      ^
Compiling .pio\build\esp32dev\lib5e1\Timezone\Timezone.cpp.o
Compiling .pio\build\esp32dev\lib03d\airline_logos\AAA.c.o
*** [.pio\build\esp32dev\src\main.cpp.o] Error 1

Thanks

**Comment by rzeldent** [comment]
Hi,

Take a look at the nomal settings.h file. There a new library is used and timezone has to be confgured.
Think that will resolve the issue...

**Comment by FonceSlimane** [comment]
Oops, sorry, you're right...
Excellent job !
