### ISSUE TITLE
It would be nice to see metric units 

### ISSUE THREAD

**Issue by kerby2000** [rzeldent/esp32-flightradar24-ttgo#34]
Now display shows ft and kns
In most of the Europe we use m and m/s

I quickly hacked 
```
IotWebConf.cpp (317)
  tft.println(String((int)((float)flight_info.altitude*0.3048)) + " m  " + String((int)((float)flight_info.speed*0.514444)) + " m/s ");
```

But you probably can make configuration out of it.

**Comment by rzeldent** [comment]
Hi Kerby,

Nice suggestion! In the world of aviation Imperial units are standard.
But in most of the world metric units are the standard. However, m/s is SI
but changed it to km/h.
So indeed, as you suggested I made an option for it... Enjoy!

Regards,

Rene
