### ISSUE TITLE
setting up the project

### ISSUE THREAD

**Issue by graememilne** [rzeldent/esp32-flightradar24-ttgo#41]
Hi ,Looks like an interesting project.
     For us clueless this appears to be a mix of both systems (linux and windows ??)
1. Which TTGO ESP32 1.14 or the 1.19 ??
2. Do we download the esp32-flightradar24-ttgo onto linux or windows computer ?? or  ( i assume it is git clone on linux ??)
3. Install Visual Studio Code (is it a windows install ??) or (is there a linux install??)    
4. Compile the upload to the  ESP32-TTGO-Display (How??)  (bullet pointer would help please)
5. Would it work on this TTGO (although screen small ) as a test until i get the TTGO featured on your page.
![IMG_20220914_110755](https://user-images.githubusercontent.com/19634301/190126720-8fb222de-b7e4-4543-9c06-d2258f9ff804.jpg)
Thank you and look forward to your reply
Graeme

**Comment by rzeldent** [comment]
Hi Greame,

The board I'm using is the LilyGO TTGO T-Display V1.1 ESP32 - with 1.14
inch TFT Display - LILYGO-G511-01-Q224 (tinytronics.nl)
<https://www.tinytronics.nl/shop/en/development-boards/microcontroller-boards/with-wi-fi/lilygo-ttgo-t-display-v1.1-esp32-with-1.14-inch-tft-display>
.
So, it is very different from the board you're using. You have a monochrome
display (and Lora transceiver) so it will not work without extensive
modifications.

Regarding the tooling, there is both a Windows and Linux install,
even MacOS so this does not matter. I suggest downloading Visual Studio
Code first and following the instructions to install PlatformIO. Uploading
is just connecting the USB-C cable, pressing the compile button and
uploading button... That's it!

 I do have some boards laying around but getting it locally is probably the
best option. I suggest a bit of patience to get the board and am sure
you'll like it!

Kind regards,

Rene

**Comment by rzeldent** [comment]
Hi Greame,

Watch out! This is another board with another CPU. It might work but
untested.
Maybe you can cancel it and order the board below instead!

I use this board: https://www.aliexpress.com/item/33050667207.html

   -
   [image: LILYGO® TTGO T-Display ESP32 Wireless WiFi Bluetooth Module 1.14
   Inch Colorful LCD Development Controller Board For Arduino]
   - [image: LILYGO® TTGO T-Display ESP32 Wireless WiFi Bluetooth Module
   1.14 Inch Colorful LCD Development Controller Board For Arduino]
   - [image: LILYGO® TTGO T-Display ESP32 Wireless WiFi Bluetooth Module
   1.14 Inch Colorful LCD Development Controller Board For Arduino]
   - [image: LILYGO® TTGO T-Display ESP32 Wireless WiFi Bluetooth Module
   1.14 Inch Colorful LCD Development Controller Board For Arduino]
   - [image: LILYGO® TTGO T-Display ESP32 Wireless WiFi Bluetooth Module
   1.14 Inch Colorful LCD Development Controller Board For Arduino]
   - [image: LILYGO® TTGO T-Display ESP32 Wireless WiFi Bluetooth Module
   1.14 Inch Colorful LCD Development Controller Board For Arduino]

LILYGO® TTGO T-Display ESP32 Wireless WiFi Bluetooth Module 1.14 Inch
Colorful LCD Development Controller Board For Arduino

Rene

**Comment by graememilne** [comment]
Hi Rene

I have cancelled the order and ordered the one you recommended to me.

Thank you for your help ,i did not notice.

I had another look at the VS Code and i have it worked out now.
Will know what to do when i get the board in due course.

Regards
Graeme

**Comment by rzeldent** [comment]
Was looking at AliExpress, also this seems a good offer https://www.aliexpress.com/item/1005003648478457.html

The initial one that you ordered might have been correct but the cheapest van an RP2040. There are also ESP32 versions so watch out when ordering. The box/shell is nice!

**Comment by graememilne** [comment]
Hi Rene
That is a good price .

The one you mentioned i ordered straight after i cancelled the first one
with case.
Need to see if i can get a case for it as i thought it nice too.
If i see one on its own i will let you know.

Regards
Graeme

**Comment by rzeldent** [comment]
Fine, let me know how it goes when you've received the TTGO T-Display!

Good luck!

**Comment by graememilne** [comment]
Hi
Update  Received the 2 TTGO   (1x with case ,1x without case)

Have 2 problems when building last night.
What did not help was a long day.
Tonight i deleted the folder and started again.
And still had build problems 5 this time .
So i sat back and had a look at the visual studio where platform.io is and
discovered the folder duplicated 2x .
So completely deleted all and started again.

SUCCESS......no problems on anything.
Could not access the 192.168.4.1 on computer.
I used whoisonmywifi to see ,but still no joy.
So went on to the android mobile and i was able to access the page to
configure .
On the lat lon range ,what does 0.20 mean ??
is it range in km or grid square 20 degrees ??

Any way got it up and running ,so have enclosed some photos (but not the
best camera on phone)
Must say i really like this .

Kind Regards
Graeme

 IMG_20220928_213138.jpg
<https://drive.google.com/file/d/12o6_1oo_nDyaIw-h5wGToMT7T5oQ6Rat/view?usp=drive_web>
 IMG_20220928_213235.jpg
<https://drive.google.com/file/d/1xuhokapDZXZ7IMtc5kd80PJKQFDQHlaR/view?usp=drive_web>
 IMG_20220928_222415.jpg
<https://drive.google.com/file/d/1IM3uRmrIkLK4Fr-Cf_wgl-C1lFMruHT1/view?usp=drive_web>
 IMG_20220928_222433.jpg
<https://drive.google.com/file/d/1ss4yNehmbBzfct45fV_EI3c51ffIyM5C/view?usp=drive_web>
 IMG_20220928_223007.jpg
<https://drive.google.com/file/d/186cxYfUWZ3Sa1J3e_k_MaNxsy-PT2G1a/view?usp=drive_web>
 IMG_20220928_223027.jpg
<https://drive.google.com/file/d/1KOUj9Q918uAOvGxPboSY9-sR_ImMzVYY/view?usp=drive_web>
 IMG_20220928_223048.jpg
<https://drive.google.com/file/d/1p8JbfU02oOeIajlhqjnaWU4AIMVVGLLg/view?usp=drive_web>
 IMG_20220928_224307.jpg
<https://drive.google.com/file/d/1P_rgrM4tKDQqFgrYXVun6ahV0RGAvEJY/view?usp=drive_web>

**Comment by rzeldent** [comment]
Hi Graeme,

I do not know exactly why your computer did not see the esp32 but the
Android did. Might have to do something with the frequency bands. The esp32
has only 2.4Ghz while modern computers have 5Ghz (and 2.4Ghz). Maybe,
otherwise; no idea...

The 0.2 is degrees. With the diameter of the earth it can be converted to
kilometers or miles. This can be seen in the status screen.

So, enjoy and let me know if you have suggestions or problems!

Kind regards,

Rene Zeldenthuis

**Comment by graememilne** [comment]
Hi Rene

Here is a suggestion ,but do not know how feasible this could be.

Flight number, change to red if a squawk code 7700,,

Regards
Graeme

**Comment by rzeldent** [comment]
Hi Graeme,

Yes, that is indeed a nice feature. Let's hope this doesn't happen but if
it does,the color should be red.

Fiddled a bit and there is a branch with your feature:
rzeldent/esp32-flightradar24-ttgo
at feature/color_squawk (github.com)
<https://github.com/rzeldent/esp32-flightradar24-ttgo/tree/feature/color_squawk>

Enjoy

Rene

**Comment by graememilne** [comment]
Thank you for very quick response.
I have installed the new version.I did have 6 warnings on the build but the
upload went ahead with no errors.

Yes indeed hope we never see these codes.

I really like the layout ,it is so unique.

Regards
Graeme

**Comment by rzeldent** [comment]
Hi Graeme,

Did found the time for a little test and found a typo in the last commit;
color was not correct (was set to background) so nothing was visible.
It Is now corrected and merged in the main branch!

Rene

**Comment by graememilne** [comment]
Good morning Rene

Yes,this morning when I went to check the screen,that's exactly what I had.
Will download new folder this evening when I come home from work.
Thank you once again.
Kind regards
Graeme
