### ISSUE TITLE
Compiling error under Micro Moustache 1.0.1

### ISSUE THREAD

**Issue by xbmcnut** [rzeldent/esp32-flightradar24-ttgo#59]
Sorry, new to Platformio inside VSC. Getting this error when compiling and that's just plain nonsense to a hardware guy like me. Anyone got any clues as Google wasn't that helpful.
```
Compiling .pio\build\esp32dev\libb10\lvgl\draw\lv_draw_line.c.o
Compiling .pio\build\esp32dev\libb10\lvgl\draw\lv_draw_mask.c.o
Compiling .pio\build\esp32dev\libb10\lvgl\draw\lv_draw_rect.c.o
Compiling .pio\build\esp32dev\libb10\lvgl\draw\lv_draw_transform.c.o
Compiling .pio\build\esp32dev\libb10\lvgl\draw\lv_draw_triangle.c.o
src/main.cpp: In function 'void handleRoot()':
src/main.cpp:190:67: error: no matching function for call to 'moustache_render(const char [], const moustache_variable_t [34])'
   auto html = moustache_render(text_html_index_html, substitutions);
                                                                   ^
In file included from src/main.cpp:20:
.pio/libdeps/esp32dev/micro-moustache/include/moustache.h:12:15: note: candidate: 'template<unsigned int n> String moustache_render(const String&, moustache_variable_t (&)[n])'
 inline String moustache_render(const String &format, moustache_variable_t (&values)[n])
               ^~~~~~~~~~~~~~~~
.pio/libdeps/esp32dev/micro-moustache/include/moustache.h:12:15: note:   template argument deduction/substitution failed:
src/main.cpp:190:67: note:   types 'moustache_variable_t' {aka 'moustache_variable'} and 'const moustache_variable_t' {aka 'const moustache_variable'} have incompatible cv-qualifiers
   auto html = moustache_render(text_html_index_html, substitutions);
                                                                   ^
*** [.pio\build\esp32dev\src\main.cpp.o] Error 1
```

**Comment by xbmcnut** [comment]
Also have this under the problems tab:
```
no matching function for call to 'moustache_render(const char [], const moustache_variable_t [34])'
```
```
initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
```

**Comment by xbmcnut** [comment]
Here's a visual representation of the error inside main.cpp.

![image](https://user-images.githubusercontent.com/1492137/220824778-a184f829-ed7e-4919-ba25-ac6a553aebdf.png)

**Comment by rzeldent** [comment]
The library for moustache has been upgraded. Please update the library!
Let me know if this helped.

**Comment by xbmcnut** [comment]
Thanks for the reply. I'd actually found that last night but updating made no difference.

![image](https://user-images.githubusercontent.com/1492137/221020200-72db30bd-d0dd-41f3-a9a8-3b990ff50437.png)

![230224-091443](https://user-images.githubusercontent.com/1492137/221020244-76b0aa7f-53eb-42c8-a328-b7a80ec3d663.png)

**Comment by rzeldent** [comment]
And maybe identical to this issue: https://github.com/rzeldent/esp32cam-rtsp/issues/34

**Comment by xbmcnut** [comment]
No new updates for any of your two projects I've got.

![image](https://user-images.githubusercontent.com/1492137/221086476-274063df-d6a9-45f8-a872-e230f85b9477.png)

**Comment by xbmcnut** [comment]
Downgraded Micro Moustache to version 10.0.0 and built successfully in 77 seconds. Uploading and working.

**Comment by ijord** [comment]
I was having the same issue under Platform.io with both Micro Mustache 1.0.0 and 1.0.1.
I fixed it by removing the "const" in front of "mustache_variable_t substitutions[] = {" on line 149.

**Comment by rzeldent** [comment]
Assume this worked!
