### ISSUE TITLE
how to remove display of the last spotted aircraft ? 

### ISSUE THREAD

**Issue by FonceSlimane** [rzeldent/esp32-flightradar24-ttgo#6]
When the last airplane is passed, this flight is still displayed on the screen as long as another is not yet entered in the area.
And it could be long, depending on the defined location.
Is there a way to display a waiting screen or blank screen after the last aircraft and an elapsed time ?

Thanks for the good work

**Comment by rzeldent** [comment]
Hi FonceSlimane,

There might be a glitch in the logic. I'll take a look at it...

**Comment by rzeldent** [comment]
Haven't tested it yet but think I saw the issue. Please take a look at branch https://github.com/rzeldent/esp32-flightradar24-ttgo/tree/bugfix/remove-last-flight.
Could you let me know if this is what you mean?

**Comment by FonceSlimane** [comment]
Your "No flights in range" screen is perfect.
Thanks a lot for your quick reply

(If you don't mind I would open another issue but just for suggestion)

**Comment by rzeldent** [comment]
Okay, wil merge this to the main branch...
