### ISSUE TITLE
Suggestion for displayed information

### ISSUE THREAD

**Issue by FonceSlimane** [rzeldent/esp32-flightradar24-ttgo#7]
Hi rzeldent,

Do you think it is possible to add flight information of the spotted airplane such as altitude and/or track, speed ?
(Maybee below the aircraft registration and type)

Thanks

**Comment by rzeldent** [comment]
Might be a bit too crowded. However, information is available...

**Comment by rzeldent** [comment]
Take a look at branch: https://github.com/rzeldent/esp32-flightradar24-ttgo/tree/feature/add-alt-heading

A bit crowdy?! What do you think

**Comment by FonceSlimane** [comment]
Well done ! 
Actually yes it's a bit crowded for me.
I made some minor changes in the file main.cpp but it spoils a little bit your work...sorry.
First I tried a size of font between 16 and 26 without any success.
So here are my changes, the first three lines are sized 26 and 16 after and I only removed the plain names of airports because of redundancy IMHO (IATA code, airport name, city name)
And I made some simplification in the file airplanes.cpp (ex: AIRBUS 320 becomes A320 and so on)


>   tft.setTextFont(font_26pt);
>   tft.println( flight_info.flight + "  " + flight_info.from + ">" + flight_info.to);
> 
>   tft.setTextFont(font_26pt); // was 16
>   tft.println(flight_info.registration + " - " + (airplane ? airplane->name : flight_info.type));
>   tft.println(String(flight_info.altitude) + "ft.  " + String(flight_info.track) + "`  " + String(flight_info.speed) + "kts");
> 
>   tft.setCursor(0, tft.getCursorY() + 8); // was + 4
>   if (from != nullptr)
>   {
>     tft.setTextFont(font_16pt); // added
>     //tft.println(from->name); // was uncommented
>     auto cursor_x = tft.getCursorX(), cursor_y = tft.getCursorY();
>     tft.pushImage(cursor_x, cursor_y + flag_margin_y_px, from->flag->width, from->flag->height, from->flag->data);
>     tft.setCursor(cursor_x + flag_width_px + flag_margin_x_px, cursor_y);
>     tft.println(from->city + String(", ") + from->country);
>   }
> 
>   tft.setCursor(0, tft.getCursorY() + 2);
>   if (to != nullptr)
>   {
>     //tft.println(to->name); // was uncommented
>     auto cursor_x = tft.getCursorX(), cursor_y = tft.getCursorY();
>     tft.pushImage(cursor_x, cursor_y + flag_margin_y_px, to->flag->width, to->flag->height, to->flag->data);
>     tft.setCursor(cursor_x + flag_width_px + flag_margin_x_px, cursor_y);
>     tft.println(to->city + String(", ") + to->country);
>   }

Thank you again for all you did.
hartelijk bedankt

**Comment by rzeldent** [comment]
Thanks for your suggestions. I removed the airport name because, yes, I agree, the city and country should be sufficient.
Additionally added the location of the aircraft.
Take a look!

**Comment by FonceSlimane** [comment]
Perfect !
It's all clear.

**Comment by rzeldent** [comment]
Added some airline logo's so even nicer. Think this issue is resolved!
